pipeline {
    agent any
    tools {
        maven 'maven'
        jdk 'JDK17'
    }
    environment {
        DOCKERHUB_CREDENTIALS = credentials('gvmc-docker-registry')
        DOCKER_IMAGE = 'mitchcatg/coordlib-servicem5:1.0.4'
    }
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                echo "PATH = ${PATH}"
                echo "JAVA_HOME = ${JAVA_HOME}"
                echo "M2_HOME = ${M2_HOME}"
                java -version
                echo "** starting notificaciones compilation"
                mvn clean package -DskipTests
                echo "** end notificaciones compilation"                            
                '''
            }
        }
        stage('Build') {
          steps {
            sh 'sudo docker build -t ${DOCKER_IMAGE} .'
          }
        }
        stage('Login & Push') {
          steps {
                sh '''
                    echo $DOCKERHUB_CREDENTIALS_PSW | sudo docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin docker.io
                    sudo docker push ${DOCKER_IMAGE}
                '''
          }
        }
    }  
}