apiVersion: tekton.dev/v1beta1 
kind: TaskRun 
metadata: 
  generateName: buildah-run- 
  namespace: diploe2-gvmc
spec: 
  taskRef: 
    name: buildah 
  params: 
    - name: IMAGE 
      value: 'docker.io/mitchcatg/coordlib-servicem5:v1.0.5'
      # ej. value: 'docker.io/cafaray/notificaciones:V2.2' 
    - name: TLSVERIFY 
      value: 'false' 
    - name: STORAGE_DRIVER 
      value: 'vfs' 
  workspaces: 
    - name: source 
      persistentVolumeClaim: 
        claimName: workspace 
    - name: dockerconfig 
      secret: 
        secretName: dockerconfig-secret